### ISSUE TITLE
Magic Missile fires multiple darts, but not in Avrae

### ISSUE THREAD

**Issue by stuartlangridge** [avrae/avrae-spells#14]
The description of _magic missile_ in Avrae is:

You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.

However, the relevant section of `spells.json` is (shortened a little)

```
  {"name": "Magic Missile",
   "automation": [
        {"type": "target", "target": "all", 
         "effects": [{"type": "damage", "damage": "{damage}" }],
         "meta": [{"type": "roll", "dice": "1d4+1[force]", "name": "damage"}]},
      {"type": "text",
        "text": "Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 force damage to its target. The darts all strike simultaneously and you can direct them to hit one creature or several."}
    ]
}
```

that is, it only fires one dart. I don't know how to describe that it fires more than one, I'm afraid, or I'd send a PR to do it. (It also adds one extra dart for each level above 1st, so casting at 2nd level fires 2 darts.)

**Comment by mommothazaz123** [comment]
Since darts can all be towards one target or multiple, the best way to handle Magic Missile is to chain `-t` (i.e. `-t ko1 -t ko2 -t ko1` sends 2 darts to KO1, and 1 to KO2). Unfortunately there's no way to make it nicer for a single target.

**Comment by stuartlangridge** [comment]
That seems a great solution. The issue is that if you cast MM without it, it rolls one die only. Is there some way in the spell definition to have it reject the command *unless* you specify an appropriate number of targets? That would entirely solve the problem, and guide people to do the right thing: it'd be much better if the command failed rather than doing a wrong thing when invoked naively, I think?

**Comment by mommothazaz123** [comment]
> Is there some way in the spell definition to have it reject the command unless you specify an appropriate number of targets?
Not at the moment, but that's a good idea for something that could be added to the list of Meta effects.
